name: arrowlogo
author: Burak Emir <burak.emir@gmail.com>
description: Web Interpreter for a Logo-like language
dependencies:
  angular: '^5.0.0'
  build_runner: '^1.6.2'
  build_test: '^0.10.2'
  build_web_compilers: '^2.6.1'

dev_dependencies:
  angular_test: '^2.0.0-beta'
  test: '^1.5.1+1'
  mockito: '^4.0.0'

environment:
  sdk: '>=2.10.0 <3.0.0'
